# Generated by Django 4.1.2 on 2022-10-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeContent',
            fields=[
                ('paragraph_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'about_me_content',
            },
        ),
    ]
