# Generated by Django 4.1.2 on 2022-10-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'framework',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=50)),
                ('pkg_type', models.CharField(choices=[('EX', 'External package'), ('IN', 'Builtin package')], max_length=2)),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('stack_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PL', 'Programming Language'), ('DB', 'Database'), ('FE', 'Front-end'), ('TS', 'Tools or Software')], max_length=2)),
            ],
            options={
                'db_table': 'tech_stack',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('frameworks', models.ManyToManyField(blank=True, to='projects.framework')),
                ('packages', models.ManyToManyField(blank=True, to='projects.package')),
                ('tech_stacks', models.ManyToManyField(to='projects.techstack')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='stack_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.techstack'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
